export const CURRENCY_SET_AMOUNT = 'CURRENCY_SET_AMOUNT';
export const CURRENCY_SET_CURRENCY = 'CURRENCY_SET_CURRENCY';
export const CURRENCY_REQUEST_RATES = 'CURRENCY_REQUEST_RATES';
export const CURRENCY_RECEIVE_RATES = 'CURRENCY_RECEIVE_RATES';
